project_name: yampl
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
archives:
  - format: tar.gz
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs"
      - "^test"
brews:
  - homepage: https://github.com/clevyr/yampl
    description: Yaml templating via line-comments
    license: GPL-3.0
    repository:
      owner: clevyr
      name: homebrew-tap
    folder: Formula
    install: |
      bin.install "{{ .ProjectName }}"
      output = Utils.safe_popen_read("#{bin}/{{ .ProjectName }}", "--completion=bash")
      (bash_completion/"{{ .ProjectName }}").write output
      output = Utils.safe_popen_read("#{bin}/{{ .ProjectName }}", "--completion=zsh")
      (zsh_completion/"_{{ .ProjectName }}").write output
dockers:
  - &dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-amd64
    use: buildx
    dockerfile: Dockerfile.goreleaser
    build_flag_templates:
      - "--platform=linux/amd64"
  - <<: *dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-armv7
    goarch: arm
    goarm: 7
    build_flag_templates:
      - "--platform=linux/arm/v7"
  - <<: *dockers
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-arm64v8
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - &docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-armv7
      - ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}-arm64v8
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Version }}
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Major }}
  - <<: *docker_manifests
    name_template: ghcr.io/clevyr/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}
nfpms:
  - id: packages
    homepage: https://github.com/clevyr/yampl
    description: Yaml templating via line-comments
    license: GPL-3.0
    maintainer: Gabe Cook <gabe@clevyr.com>
    formats:
      - deb
      - rpm
publishers:
  - name: fury.io
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -sf -Fpackage=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/clevyr/
